### PR TITLE
docs/examples/scripts/simul_cbox_movie.py for movie in README

### PR DESCRIPTION
**Pull request by paugier**
For #156. Supersede #177 (easier for me to open a new PR).

Then, we need to decide about the values of the parameters to create a nice movie (nicely moving and with small scales). @akhoubani you have experience with this flow / simulations. Tell us about the parameters!

### CODE REVIEW

**Comment by paugier** [comment]
Needs https://foss.heptapod.net/fluiddyn/fluidsim/-/merge_requests/318 !

**Comment by akhoubani** [comment]
Do you agree with the mixed case convection?

**Comment by paugier** [comment]
> Do you agree with the mixed case convection?

What do you mean? I don't understand how I can "agree"? Except if I miss something, we didn't talk about the mixed case convection? Your script in #177 what not mixed case convection.

However, using the mixed case convection could be nice for the movie. So if your question was "could we use the mixed case convection", yes, it could be a good idea.

I have another question @akhoubani : could we have a turbulent unstationary statistically steady state with small scales in 2d side wall convection? If yes, at which Ra, Pr, aspect ratio ?

**Comment by akhoubani** [comment]
> What do you mean? I don't understand how I can "agree"? Except if I miss something, we didn't talk about the mixed case convection? Your script in #177 what not mixed case convection.

I accept I was not clear enough. Yes, the script in #177 was not mixed case convection. 

> 
> I have another question @akhoubani : could we have a turbulent unstationary statistically steady state with small scales in 2d side wall convection? If yes, at which Ra, Pr, aspect ratio ?

A "nicely moving and with small scales" movie is not clear to me, but the parameters, A=1.0, Pr=0.71, Ra=1.0e10, may answer this question and https://github.com/snek5000/snek5000/pull/201#issue-1449810822.

**Comment by paugier** [comment]
So could you precise what you meant when you wrote "Do you agree with the mixed case convection?" ?

**Comment by akhoubani** [comment]
> So could you precise what you meant when you wrote "Do you agree with the mixed case convection?" ?

Yes, I can precisely (in my view and considering your knowledge on the subject) explain what I meant from this comment.
I was thinking about including the mixed case convection with desirable parameters to produce a nice animation ("nice animation" also needs a precise description) of the development of flow structures in the box.

**Comment by ashwinvis** [comment]
If I may... I think by nice animation, Pierre meant a visually appealing simulation with the flow breaking down into smaller structures quickly. It might be less exciting in terms of physics, but that's OK.

> turbulent unstationary statistically steady state with small scales in 2d side wall convection? If yes, at which Ra, Pr, aspect ratio ?

And there Pierre was hinting at what he was looking for.

Sent from Proton Mail mobile

-------- Original Message --------

**Pull request merged**
