### PR TITLE
Add delta_T to conftest.py

### PR DESCRIPTION
**Pull request by akhoubani**

### CODE REVIEW

**Comment by ashwinvis** [comment]
I don't see where delta_T_lateral is defined. Is it in your personal fork?

**Comment by akhoubani** [comment]
> I don't see where delta_T_lateral is defined. Is it in your personal fork?

Yes, we changed a bit the solver. You could see it in [this pull request](https://github.com/snek5000/snek5000-cbox/pull/18). But I encountered some issues on the server.

**Comment by paugier** [comment]
This PR is not even merged, so we don't want to have this change in a snek5000 test yet.

Anyway, the snek5000-cbox test in snek5000 is for snek5000-cbox stable (a Git branch in the repo https://github.com/snek5000/snek5000-cbox/tree/stable).

**Comment by akhoubani** [comment]
> This PR is not even merged, so we don't want to have this change in a snek5000 test yet.
> 
> Anyway, the snek5000-cbox test in snek5000 is for snek5000-cbox stable (a Git branch in the repo https://github.com/snek5000/snek5000-cbox/tree/stable).

Ok. Thanks for your comments.

**Pull request closed without merging**
