### PR TITLE
Add CITATION.cff

### LINKED ISSUE #213: Github Citation file format
- https://github.blog/2021-08-19-enhanced-support-citations-github/

### PR DESCRIPTION
**Pull request by paugier**
Fixes #213. Related to #132.

I guess it should be merged after 0.8.0 is released.

### CODE REVIEW

**Comment by ashwinvis** [comment]
Actually before 0.8.0. But first I should obtain a DOI from Zenodo.

**Comment by paugier** [comment]
Do you understand the checks `build (3.8) Expected — Waiting for status to be reported            Required` ? which do not run?

**Comment by ashwinvis** [comment]
No, no clue.

**Comment by ashwinvis** [comment]
Could it be because in matrix.python-version, 3.8 and 3.9 are not quoted?

**Comment by paugier** [comment]
In tried with quotes in https://github.com/snek5000/snek5000/pull/209 but it's not better...

**Comment by paugier** [comment]
This was a problem with the configuration of the protection of the main branch. I changed it and it is now fixed.

**Pull request merged**
