### PR TITLE
WIP: Replace shell script with Python code

### LINKED ISSUE #104: Execution hangs when snakemake + mpiexec is used with >= 2 SLURM cluster nodes
Upstream bug.

https://github.com/snakemake/snakemake/issues/1248
https://github.com/snakemake/snakemake/issues/1227

Possible solution, try to replace `shell:` with `run:` so that we can "natively" call mpiexec.

### PR DESCRIPTION
**Pull request by ashwinvis**
Needs more work.

When done, fixes #104

### CODE REVIEW

**Comment by paugier** [comment]
@ashwinvis what is the status of this PR? Should it be continued?

**Comment by ashwinvis** [comment]
This did not help the issue I was having with SLURM. Does it work fine in OAR with multiple nodes?

**Comment by paugier** [comment]
@akhoubani could you please answer to this question? I remember that you had problems with simulations on more than one node. What was your problem? It is described in an issue?

**Comment by akhoubani** [comment]
> @akhoubani could you please answer to this question? I remember that you had problems with simulations on more than one node. What was your problem? It is described in an issue?

It works fine with OAR. I can submit on one node and also on more than one node. The problem was from the submitting script not including the `nb_nodes`. In the new scripts I included the `nb_nodes`.

**Comment by akhoubani** [comment]
I am not aware of SLURM case.

**Comment by paugier** [comment]
@ashwinvis I let you close this PR if you think this should not be finalized.

**Comment by ashwinvis** [comment]
I do not have an active HPC project to test and reproduce this. It is reassuring that OAR does not have this issue. I will close this for now.

**Comment by ashwinvis** [comment]
As a future note, I did not recall that this change helped my issue I was facing in NSC Tetralith

**Pull request closed without merging**
