### PR TITLE
Delete .gitmodules

### PR DESCRIPTION
**Pull request by paugier**
Having .gitmodules with a repo that changed in time create issues with hg + hg-git. It is also much better for the developers to be in the same situation than the users (i.e. without lib/Nek5000).

We now assume than the environment variable `NEK_SOURCE_ROOT` is defined and points to Nek5000 top level directory.

### CODE REVIEW

**Comment by paugier** [comment]
Locally, the test `pytest -v --runslow -s tests/test_restart.py::test_restart` blocks with:

```
Step      8, t= 1.6000000E-03, DT= 2.0000000E-04, C=  0.009 2.4423E-01 2.9558E-02
             Solving for fluid
          8  Project VELX           1.8171E+00   2.4929E+01   1.3720E+01   3   8
          8  Hmholtz VELX       3   2.8236E-11   8.7950E-01   1.0000E-08
          8  Project VELY           1.9382E+00   5.9687E+00   3.0795E+00   3   8
          8  Hmholtz VELY       3   2.5780E-11   7.2506E-01   1.0000E-08
          8  Project VELZ           2.9691E-01   4.8689E-01   1.6399E+00   3   8
          8  Hmholtz VELZ       2   8.1502E-09   8.5089E-02   1.0000E-08
          8  Project PRES           3.0976E+00   2.7135E+01   8.7601E+00   3  20
          8  U-PRES gmres     120   6.1610E-07   3.3792E-04   1.0000E-08   1.1839E-02   2.8138E-02
          8  Volflow X              1.6000E-03   9.9066E-01   1.3622E-03   9.1561E+00   9.1575E+00
          8  Fluid done  1.6000E-03  3.0834E-02
  [STAT] Average compute
  [STAT] Global sum
gs_setup: 216 unique labels shared
   pairwise times (avg, min, max): 2.28098e-06 2.2155e-06 2.3244e-06
   crystal router                : 2.1445e-06 2.1336e-06 2.1566e-06
   all reduce                    : 2.6965e-06 2.6874e-06 2.7056e-06
   used all_to_all method: crystal router
   handle bytes (avg, min, max): 13276 11764 16084
   buffer bytes (avg, min, max): 4464 4032 5184
  [STAT] Writing stat file
       FILE:./session_00/c2Dphill0.f00001                                                                                                       
       FILE:./session_00/stsphill0.f00002
```

**Comment by paugier** [comment]
@ashwinvis and @akhoubani your help would be very appreciated here because I don't understand!

**Comment by paugier** [comment]
I'm going to merge this PR to see if it works with readthedocs.

**Comment by ashwinvis** [comment]
@paugier I think you have to see if stat.f and stat_IO.f have been updated from KTH

**Pull request merged**
